#!/bin/sh

# ======================
#    Bootstrap Script
#
# @author Luke Whrit
# ======================

if [ ${EUID:-$(id -u)} -eq 0 ]; then # Ensure the script runs as the root user
	# Because Git submodule commands cannot operate without a work tree, they
	# must be run from within $HOME (assuming this is the root of your dotfiles)
	cd "$HOME" || exit

	echo "~> Initializing submodules"
	yadm submodule update --recursive --init

	echo "~> Running pre-bootstrap routines"

	# Make sure commands we need are installed

	if ! command -v pacman > /dev/null 2>&1; then
		echo "~> Command 'pacman' could not be found"
		exit 1
	fi

	# Git configuration
	echo -n "What's your Git username: "
	read GIT_USERNAME

	echo -n "What's your Git email: "
	read GIT_EMAIL

	git config user.name $GIT_USERNAME
	git config user.email $GIT_EMAIL

	if ! command -v yay > /dev/null 2>&1; then
		cd /tmp/
		pacman -S --needed git base-devel
		cd /tmp/
		git clone "https://aur.archlinux.org/yay.git"
		cd yay
		makepkg -si
	fi

	echo "~> Installing programs"
	echo "~> This script does not yet install programs"
	exit 0
fi
