#!/bin/bash

# Reload helpers
alias \
	reload.zsh='source $ZDOTDIR/.zshrc' \
	reload.env="source ~/.zshenv" \
	reload.term="source ~/.zshenv && source ~/.zshrc"

# Testing
alias \
	checkemoji="curl https://unicode.org/Public/emoji/13.0/emoji-test.txt | less" \
	checkutf8="curl https://www.cl.cam.ac.uk/~mgk25/ucs/examples/UTF-8-demo.txt | less"

# Make commands faster and more modern
alias \
	cat="bat" \
	du="dust" \
	grep="rg" \
	ps="procs"

# Files
alias \
	..="cd .." \
	explorer="xdg-open" \
	explore="xdg-open ." \
	sizeof="du" \
	ls="lsd"

# Packaging
alias \
	unlock="sudo rm /var/lib/pacman/db.lck" \
	cleanup='sudo pacman -Rns $(pacman -Qtdq)' # Remove orphaned packages

# Common Options
alias \
	mkdir="/usr/bin/mkdir -p" \
	mongod="mongod --dbpath=\"/home/luke/.config/mongo/data/db\"" \
	lunar="lunar --config ~/.config/lunar.yaml" \
	df="df -h" \
	free="free -m"

# Git
alias \
	czc="git add . && git-cz && git push" \
	yac="yadm commit -am "$(date +%s)" && yadm push" \
	czi="commitizen init cz-conventional-changelog --yarn --dev --exact"

# Editors
alias \
	vim="nvim" \
	nv="nvim" \
	subl3="LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 subl3"

# Safety
alias \
	mv="mv -i" \
	rm="rm -i" \
	cp="cp -i"

# Miscellaneous
alias \
	"ip?"="curl icanhazip.com" \
	gs="git status" \
	rr="curl -s -L https://raw.githubusercontent.com/keroserene/rickrollrc/master/roll.sh | bash"

# functions
chpwd() { # run ls after changing directory
  emulate -L zsh
  ls
}

tarr () { # common 
  tar -pczf "$1" "$2"
}

untarr () {
  tar -pxzf "$1"
}

ex ()
{
  if [ -f $1 ] ; then
    case $1 in
      *.tar.bz2)   tar xjf $1   ;;
      *.tar.gz)    tar xzf $1   ;;
      *.bz2)       bunzip2 $1   ;;
      *.rar)       unrar x $1   ;;
      *.gz)        gunzip $1    ;;
      *.tar)       tar xf $1    ;;
      *.tbz2)      tar xjf $1   ;;
      *.tgz)       tar xzf $1   ;;
      *.zip)       unzip $1     ;;
      *.Z)         uncompress $1;;
      *.7z)        7z x $1      ;;
      *.deb)       ar x $1      ;;
      *.tar.xz)    tar xf $1    ;;
      *.tar.zst)   unzstd $1    ;;      
      *)           echo "'$1' cannot be extracted via ex()" ;;
    esac
  else
    echo "'$1' is not a valid file"
  fi
}


