#!/bin/bash

# source reload
alias \
  reload.zsh='source $ZDOTDIR/.zshrc' \
  reload.profile="source ~/.bash_profile" \
  reload.term="source ~/.bash_profile && source ~/.zshrc"

# testing
alias \
  checkemoji="curl https://unicode.org/Public/emoji/13.0/emoji-test.txt | less" \
  checkutf8="curl https://www.cl.cam.ac.uk/~mgk25/ucs/examples/UTF-8-demo.txt | less"

# speed and modernity
alias \
  cat="<" \
  du="dust" \
  grep="rg" \
  ps="procs"

# files
alias \
  ..="cd .." \
  explorer="xdg-open" \
  explore="xdg-open ." \
  sizeof="du -h" \
  duh="du -h" \
  ls="lsd"

# Common Options
alias \
  mkdir="/usr/bin/mkdir -p" \
  mongod="mongod --dbpath=\"/home/luke/.config/mongo/data/db\"" \
  lunar="lunar --config ~/.config/lunar.yaml" \
  subl3="LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 subl3"

# git
alias \
  czc="git add . && git-cz && git push" \
  yac="yadm commit -am "$(date +%s)" && yadm push" \
  czi="commitizen init cz-conventional-changelog --yarn --dev --exact"

# editors
alias \
  vim="nvim" \
  nv="nvim"

# safety
alias \
  mv="mv -i" \
  rm="rm -i"

# misc
alias \
  "ip?"="curl icanhazip.com" \
  gs="git status"

# functions
chpwd() { # run ls after changing directory
  emulate -L zsh
  ls
}

tarr () { # common 
  tar -pczf "$1" "$2"
}

untarr () {
  tar -pxzf "$1"
}
