#!/bin/sh

sxhkd &
feh --bg-fill ~/pics/Wallpapers/wallpaper.jpg
picom & 
imwheel --kill --buttons "45" &
/home/luke/.config/polybar/launch.sh
start-pulse-audiox11 &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          20

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Brave desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
