#!/bin/sh

# Program autostrat
sxhkd &
picom &
imwheel --kill --butons "45"
start-pulse-audiox11 &

feh --bg-fill ~/pics/Wallpapers/wallpaper.jpg
/home/luke/.config/polybar/launch.sh

# BSPWM configuration

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           20
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color  \#000
bspc config active_border_color  \#000
bspc config focused_border_color \#000

bspc rule -a Gimp                desktop='^8' state=floating follow=on
bspc rule -a mplayer2            state=floating
bspc rule -a Kupfer.py           focus=on
bspc rule -a Screenkey           manage=off
